### PR TITLE
yamllint-clean

### PR DESCRIPTION
**Pull request by NoseyNick**
Ran through the `yamllint` tool https://yamllint.readthedocs.io/
Fixed all the **errors** (mostly trailing spaces and some slightly-wrong indentation)
One **warning** remains:
```
18:1      warning  missing document start "---"  (document-start)
```
Didn't want to fix that one in case anyone is making unwise assumptions whilst parsing with technically-incorrect YAML parsers.

Incorporates / Assumes #50 and #51 are already merged, builds atop those. Alternatively, this can replace both of those. Feel free to edit PR "base" accordingly.

Reviewers should be able to ask GitHub to :gear: " :ballot_box_with_check: Hide whitespace changes" and see no other changes (except those already seen in #50 / #51)

### CODE REVIEW

**Comment by hessu** [comment]
Hi,

I'm not a great fan of these whitespace commit changes, and overall not too worried about a few extra whitespaces here and there either. Especially since the current tooling does not make them go away automatically in the future. There will be new ones coming later on if there's no process to remove them, and in particular I'm not one to manually remove them even if some linter would like to see them gone.

Also, please make one PR for one topic, it is easier to merge it without merging the others yet.

I'll add the "---" document start (17b3ab37c82181aebd3d59f465545c2837bb6abd), it's accepted by the parsers I use and should be accepted by others just as well. Thanks!

**Comment by hessu** [comment]
If you'd like to see the linter pass, please describe why. Feel free to try to convince me, I am open to feedback as such.

**Comment by NoseyNick** [comment]
Mostly I was trying to make sure **my new changes** were legit "valid YAML", and noticed
1. Well **probably** yes, but...
2. other parts of the file weren't.

Would have been easier to spot my own mistakes if it was "known good" before I began   :shrug:

**Comment by NoseyNick** [comment]
Also feels like Postel's Law applies here - "be conservative in what you send, be liberal in what you accept". Even though many YAML parsers will be lenient in what they accept, and tolerate all sorts of even worse invalid YAML, it's most polite and most technically correct to be strict in what you send into them.   :shrug: 

... but again, your repo, your rules, you want technically-invalid YAML, that's **absolutely** your prerogative, I'm not gonna stop you even if I wanted to   :rofl:

Stay awesome!   :grinning:  Live Long And Prosper! :vulcan_salute:

**Comment by hessu** [comment]
I'm not sure I understand how I "want technically-invalid YAML". I believe the YAML is fine and valid right now? There might be some whitespace here and there, but that doesn't make it invalid.

**Comment by NoseyNick** [comment]
`yamllint` referred to the trailing-spaces and "wrong indentation" as `errors` rather than `warnings`. You are obviously welcome to disagree with `yamllint` and/or its authors.

**Pull request closed without merging**
